# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.GPG }}
        gpg-passphrase: GPG_PASSPHRASE

    - name: Publish to Sonatype Maven
      run: mvn --batch-mode clean deploy -DskipTests
      env:
        OSSRH_USERNAME: jayxu
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
        MAVEN_USERNAME: jayxu
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
